name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
    
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: | 
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
            assets/github-contribution-grid-snake.gif
            assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.
        with:
          branch: master
          build_dir: assets
          message: 'Generate Contribution Snake' 
